
# configuration file for continuous integration testing using travis-ci.com

dist:
 - jammy
 
python: 3.8

services:
  - docker

script:
# build Docker container
- docker build -t nnenum .

# run tests
- docker run nnenum
